//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Linq;
using NUnit.Framework;

namespace ImageScraper
{
	[TestFixture]
	public class ExtensionFilterTests
	{
		[Test]
		public void FiltersExcludedExtensions() {
			var filter = new ExtensionFilter (new string[] {
				"png",
				"jpg"
			});
			var results = filter.Filter (new Uri[] {
				new Uri("http://www.test.com/test1.gif")
			}).ToList ();

			Assert.IsEmpty(results);
		}
		
		[Test]
		public void AllowsIncludedExtensions() {
			var filter = new ExtensionFilter (new string[] {
				"png",
				"jpg"
			});

			var uri = new Uri ("http://www.test.com/test1.png");
			var results = filter.Filter (new Uri[] {uri}).ToList ();
			
			Assert.Contains(uri, results);
		}
	}
}

