//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Net;

namespace ImageScraper
{
	public class FileDownloader : IFileDownloader
	{
		private WebClient _client;

		public FileDownloader ()
		{
			_client = new WebClient ();
		}

		public string DownloadString(Uri uri) {
			return _client.DownloadString (uri);
		}

		public void DownloadFile(Uri uri, string path) {
			_client.DownloadFile (uri, path);
		}

		// Download each of the specified files into a directory, using their current names and extensions
		public void DownloadFiles(IEnumerable<Uri> uris, string directory) {
			foreach (var uri in uris) {
				var filename = uri.Segments[uri.Segments.Length-1];
				var path = System.IO.Path.Combine (directory, filename);
				this.DownloadFile (uri, path);
			}
		}
	}
}

