//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;

namespace ImageScraper
{
	public interface IFileDownloader
	{
		string DownloadString (Uri uri);
		void DownloadFile (Uri uri, string path);
		void DownloadFiles (IEnumerable<Uri> uris, string directory);
	}
}

